name: Build and Push Docker Images

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Load Docker Environment Variables
        working-directory: docker
        run: |
          echo "PYICUB_IMAGE_NAME=$(grep PYICUB_IMAGE_NAME .env | cut -d '=' -f2-)" >> $GITHUB_ENV

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Base Image
        working-directory: docker
        run: |
          ./build.sh
          docker push $PYICUB_IMAGE_NAME
          docker push $PYICUB_FRONTEND_IMAGE_NAME
